Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # hand_rec
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator hand_rec/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/hand_rec.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/hand_rec.py", line 84, in on_event
img.shape=torch.Size([3, 192, 256])
          im1, scale, pad = resize_pad_tensor(image)
        File "/Users/dave/dev/ultra/dora_webcam/hand_rec.py", line 41, in resize_pad_tensor
          print(f"{padh.shape=}")

      AttributeError: 'int' object has no attribute 'shape'

Location:
    binaries/runtime/src/operator/python.rs:29:9
