Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # hand_rec
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator hand_rec/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/hand_rec.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/hand_rec.py", line 150, in on_event
landmarks.shape=torch.Size([0, 21, 3])
          send_output(
flags=tensor([])

landmarks.shape=torch.Size([1, 21, 3])
      RuntimeError: invalid `data` type, must by `PyBytes` or arrow array
flags=tensor([0.0293], device='mps:0', grad_fn=<SigmoidBackward0>)

      Location:
          binaries/runtime/src/operator/python.rs:379:17

Location:
    binaries/runtime/src/operator/python.rs:29:9
