Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # hand_rec
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator hand_rec/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/hand_rec.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/hand_rec.py", line 98, in on_event
          img, affine, box = self.hand_regressor.extract_roi(image, xc, yc, theta, scale)
        File "/Users/dave/dev/ultra/dora_webcam/torch_mediapipe/blazebase.py", line 192, in extract_roi
          img = cv2.warpAffine(frame, M, (res,res))#, borderValue=127.5)

      error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'warpAffine'
      > Overload resolution failed:
      >  - src is not a numpy array, neither a scalar
      >  - Expected Ptr<cv::UMat> for argument 'src'


Location:
    binaries/runtime/src/operator/python.rs:29:9
